apiVersion: "v1"
name: "splice"
version: "0.2.0"
type: "getter/v1"
runtime: subprocess
config:
  protocols:
    - "splice"
runtimeConfig:
  protocolCommands:
    - protocols:
        - "splice"
      platformCommand:
        - command: "helm-splice"
  platformHooks:
    install:
      - os: linux
        arch: ""
        command: "bash"
        args: ["-c", "cd \"${HELM_PLUGIN_DIR}\" && \"${HELM_PLUGIN_DIR}/scripts/install-binary.sh\""]
      - os: darwin
        arch: ""
        command: "bash"
        args: ["-c", "cd \"${HELM_PLUGIN_DIR}\" && \"${HELM_PLUGIN_DIR}/scripts/install-binary.sh\""]
    update:
      - os: linux
        arch: ""
        command: "bash"
        args: ["-c", "cd \"${HELM_PLUGIN_DIR}\" && \"${HELM_PLUGIN_DIR}/scripts/install-binary.sh\""]
      - os: darwin
        arch: ""
        command: "bash"
        args: ["-c", "cd \"${HELM_PLUGIN_DIR}\" && \"${HELM_PLUGIN_DIR}/scripts/install-binary.sh\""]