name: "splice"
version: "0.1.0"
usage: "Splicing values files using inline placeholders"
description: "Helm downloader plugin to recursively splice values files"
downloaders:
  - command: "helm-splice"
    protocols:
      - "splice"

hooks:
  install: "scripts/install-binary.sh"
  update: "scripts/install-binary.sh"